## Modifications to logic.
[logic]
## Logic Mode. Choose one of: "Normal", "Hard", "GlitchBasic", "GlitchAdvanced", "GlitchHell", or "NoLogic"
mode = "Normal"
## Guarantees one of the following weapons will be placed in Ravio's Shop: Sword, Bow, Hammer, Fire Rod, Ice Rod, or Bombs
assured_weapon = false
## The Bell will be placed in Ravio's Shop
bell_in_shop = false
## The Pouch will be placed in Ravio's Shop
pouch_in_shop = false
## The Pegasus Boots will be placed in Ravio's Shop
boots_in_shop = false
## Include the Super Lamp and Super Net in the shuffled item pool
super_items = false
## Exclude all minigames (Cucco Ranch, both Rupee Rushes, Hyrule Hotfoot, Treacherous Tower, and Octoball Derby)
minigames_excluded = false
## Skip the Trials in Lorule Castle
skip_trials = false
## Guarantees the Bow of Light will be placed *somewhere* in Lorule Castle (including possibly Zelda)
bow_of_light_in_castle = false
## Swordless Mode. Removes all Swords from the game. You will need the Net to play Tennis with Yuganon.
swordless_mode = false

## Game Options
[options]
## Experimental option to change Hyrule's lighting until you visit Lorule for the first time.<br><br>WARNING: Enabling this option may cause performance issues while your game is being randomized.
night_mode = false

## Excludes a specific check from having progression items. A random junk item will be placed there instead.
[exclusions]
"exclusions" = [
#   "Great Rupee Fairy",
#   "Thief Girl Cave"
#   "Master Sword Pedestal"
]