## Modifications to the game's logic.
[logic]
## Disables the requirement for the lamp in dark areas.
# dont_require_lamp_for_darkness = false
## Requires the seller's golden bee for the Bee Badge check.
# require_golden_bee_for_sale = false
## Allows all of the keys to be placed in an order where one or more softlocks can occur.
# unsafe_key_placement = false
## Place items using logic that potentially requires glitches to complete
# glitched_logic = false
## Shuffles the location of Ravio's Bracelet
# shuffle_bracelet = false

## Excludes certain locations from having progression items.
[exclude]
## Use the names from the spoiler log.
# [exclude.Hyrule]
