## Modifications to the game's core mechanics.
[modifications]
## Enabled the Y button from the start.
# y_button_enabled = false

## Modifications to logic.
[logic]
## Disables lamp requirement for dark areas.
# dont_require_lamp_for_darkness = false
## Requires seller's golden bee for Bee Badge check.
# require_golden_bee_for_sale = false
## Allows keys to be placed in an order that can lead to softlocks.
# unsafe_key_placement = false
## Place items using logic that potentially requires glitches to complete
# glitched_logic = false
## Shuffles the location of Ravio's Bracelet
# shuffle_bracelet = false

## Modifications to certain items.
[items]
## Skips the Captain's Sword.
# captains_sword = 'Unchanged'
## Shuffles the Borrowed Sword.
# borrowed_sword = 'Unchanged'
## Shuffles the Lamp.
# lamp = 'Unchanged'
## Skips Ravio's first bracelet.
# first_bracelet = 'Unchanged'

## Modifications to game behavior.
[behavior]
## Starts the game in a pseudo-post-Sanctuary state.
# open = false
## Enables the barrier around Hyrule Castle from the start.
# barrier = 'Unchanged'

## Excludes certain locations from having progression items.
[exclude]
## Use the names from the spoiler log.
# [exclude.Hyrule]
